// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdNrGNGaFBi2U4gvMplxqinnYqS45QEyI',
    appId: '1:835561852078:web:a18b0dc7073c2b235c313f',
    messagingSenderId: '835561852078',
    projectId: 'ecomun',
    authDomain: 'ecomun.firebaseapp.com',
    storageBucket: 'ecomun.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9HlTXDltzS9XKLT_yqF0oWfWs3qHBDFQ',
    appId: '1:835561852078:android:715701601bb4db755c313f',
    messagingSenderId: '835561852078',
    projectId: 'ecomun',
    storageBucket: 'ecomun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjMDUrfmnlyrKJreVORUaoziH9uyg7nR4',
    appId: '1:835561852078:ios:f7f550eb106d2e065c313f',
    messagingSenderId: '835561852078',
    projectId: 'ecomun',
    storageBucket: 'ecomun.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjMDUrfmnlyrKJreVORUaoziH9uyg7nR4',
    appId: '1:835561852078:ios:f7f550eb106d2e065c313f',
    messagingSenderId: '835561852078',
    projectId: 'ecomun',
    storageBucket: 'ecomun.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdNrGNGaFBi2U4gvMplxqinnYqS45QEyI',
    appId: '1:835561852078:web:87f0b4d8bd4c5b465c313f',
    messagingSenderId: '835561852078',
    projectId: 'ecomun',
    authDomain: 'ecomun.firebaseapp.com',
    storageBucket: 'ecomun.firebasestorage.app',
  );
}
